---
- name: Setup dev environment
  hosts: localhost

  tasks:
  - name: Install zsh
    become: true
    ansible.builtin.apt:
      update_cache: yes
      name: zsh
      state: present

  - name: Install curl
    become: true
    ansible.builtin.apt:
      update_cache: yes
      name: curl
      state: present

  - name: Install oh-my-zsh
    ansible.builtin.shell: echo "Y\n" | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: Install antigen
    ansible.builtin.shell: curl -sL git.io/antigen > antigen.zsh

  - name: Install oh-my-posh
    ansible.builtin.shell: curl -s https://ohmyposh.dev/install.sh | bash -s

  - name: Create fonts directory if it doesn't exist
    ansible.builtin.file:
      path: $HOME/.fonts
      state: directory

  - name: Download JetBrains Mono Nerd Font
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
      dest: $HOME/.fonts
      remote_src: yes

  - name: Install JetBrains Mono Nerd Font
    ansible.builtin.shell: fc-cache -f -v

  - name: Install Kitty Terminal
    ansible.builtin.shell: curl -sL https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin | launch=n

  - name: Setup Kitty Desktop Links
    ansible.builtin.script: ./config/kitty-desktop.sh

  - name: Install tmux
    become: true
    ansible.builtin.apt:
      update_cache: yes
      name: tmux
      state: present

  - name: Install tmux plugin manager
    ansible.builtin.shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm -q

  - name: Install tmuxifier
    ansible.builtin.shell: git clone https://github.com/jimeh/tmuxifier.git ~/.tmuxifier -q

  - name: Copy kitty config
    ansible.builtin.copy:
      src: ./config/kitty.conf
      dest: $HOME/.config/kitty/kitty.conf

  - name: Copy zsh config
    ansible.builtin.copy:
      src: ./config/.zshrc
      dest: $HOME/.zshrc

  - name: Copy oh-my-posh config
    ansible.builtin.copy:
      src: ./config/oh-my-posh-config.omp.json
      dest: $HOME/oh-my-posh-config-omp.json
...
